### ISSUE TITLE
Add option to set prompt title?

### ISSUE THREAD

**Issue by Ajaymamtora** [divagueame/lacasitos.nvim#1]
I wrote a wrapper but want to be able to set a title:

```lua
function M.prompt_confirm(prompt_text, yes_callback, no_callback)
  local lacasitos = require("lacasitos")

  local options = { "Yes", "No" }

  local selected_option = lacasitos.choose_option(options, prompt_text)

  if selected_option == "Yes" then
    yes_callback()
  elseif selected_option == "No" then
    no_callback()
  else
    print("No option selected.")
  end
end
```

**Comment by divagueame** [comment]
Hi Ajaymamtora, thanks for opening the issue. 
Will definitely add the option to pass a options config for the float window soon. 
Might also add the option to add a callback per option too.

**Comment by divagueame** [comment]
I just added the options config on setup and for individual choose_option calls. Updated the docs with details.
